- id: '1580448315959'
  alias: MyAutomation
  description: ''
  trigger:
  - entity_id: binary_sensor.cabin7
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: The sun is {% if is_state('sun.sun', 'above_horizon') %}up{% else %}down{%
        endif %}!
      title: test
    service: notify.outlook
